Repository jazzband/django-axes, pull requests merged in 2018-04, with the labels that each got.

#315 use an authentication backend to check if user is locked out.
  axes/backends.py
  axes/conf.py
  axes/decorators.py
  axes/utils.py
  docs/configuration.rst
Labels: enhancement

#325 Add proxy and client IP configuration settings and documentation
  axes/attempts.py
  axes/conf.py
  axes/signals.py
  axes/tests/test_access_attempt.py
  axes/utils.py
  docs/configuration.rst
  setup.py
Labels: enhancement

#330 Bump version to 4.2.1
  CHANGES.txt
  axes/__init__.py
  docs/conf.py
Labels: bug, python2

#332 Fix call to undefined variable ua in _get
  axes/attempts.py
Labels: bug, enhancement

#335 Version 4.3.1
  CHANGES.txt
  axes/__init__.py
Labels: enhancement
